name: Build

on:
  push:
    branches: [ "main", "cmake", dev]
  pull_request:
    branches: [ "main", "cmake", dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - { name: linux_gcc,   os: ubuntu-latest,  cc: gcc,   shell: bash }
        - { name: linux_clang, os: ubuntu-latest,  cc: clang, shell: bash }
        - { name: win32_msvc,  os: windows-latest, cc: msvc,  shell: pwsh, cmake_config: "-A Win32", cmake_build: "--config Release"}
        - { name: win64_msvc,  os: windows-latest, cc: msvc,  shell: pwsh, cmake_config: "-A x64",   cmake_build: "--config Release"}
        - { name: win64_gcc,   os: windows-latest, cc: gcc,   shell: msys2 }
        - { name: win64_clang, os: windows-latest, cc: clang, shell: msys2 }
        - { name: macos_clang, os: macos-latest,   cc: clang, shell: bash  }

    name: ${{ matrix.name }}
    env:
      CC: ${{ matrix.cc }}
    defaults:
      run:
        shell: '${{ matrix.shell }} {0}'

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSYS2
      if: runner.os == 'Windows' && (matrix.cc == 'gcc' || matrix.cc == 'clang')
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-cmake

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. ${{ matrix.cmake_config }}
        cmake --build . -v ${{ matrix.cmake_build }}
        cmake --install . --prefix ../${{ matrix.name }} ${{ matrix.cmake_build }}

    - name: Test
      run: |
        cd ${{ matrix.name }}
        ./bin/float2half ./float2half_result.csv
        ./bin/half2float ./half2float_result.csv

    - name: Create Graphs
      shell: bash
      run: |
        python -m pip install matplotlib
        mkdir graph
        cd graph
        python ../scripts/graph.py ../${{ matrix.name }}/float2half_result.csv
        python ../scripts/graph.py ../${{ matrix.name }}/half2float_result.csv
        cd ..
        # move files into place for upload
        mkdir upload_dir
        mv ./${{ matrix.name }} ./upload_dir/
        mv ./graph/images ./upload_dir/

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          upload_dir/*