name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build and test
      run: sh ./build.sh

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: create graphs
      shell: bash
      run: |
        python -m pip install matplotlib
        python graph.py float2half_result.csv

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: float2half_test_linux
        path: |
          float2half_result.csv
          float2half
          half2float
          images/*.png

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: build and test
      run: sh ./build.sh

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: create graphs
      shell: bash
      run: |
        python -m pip install matplotlib
        python graph.py float2half_result.csv

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: float2half_test_macos
        path: |
          float2half_result.csv
          float2half
          half2float
          images/*.png

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
          arch: amd64

    - name: build and test
      run: cmd /c build.bat

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: create graphs
      shell: bash
      run: |
        python -m pip install matplotlib
        python graph.py float2half_result.csv

    - name: "upload artifact"
      uses: actions/upload-artifact@v3
      with:
        name: float2half_test_win64
        path: |
          float2half_result.csv
          float2half.exe
          half2float.exe
          images/*.png